import test from 'node:test';
import assert from 'node:assert/strict';
import { parsePnpmLockfile, parsePnpmLockfiles } from '../packages/core/dist/manifest/lockfiles/pnpm.js';
import { parseYarnLockfile } from '../packages/core/dist/manifest/lockfiles/yarn.js';
import { parseBunLockfile, parseBunLockfiles } from '../packages/core/dist/manifest/lockfiles/bun.js';
import { parsePackageJson } from '../packages/core/dist/manifest/package-json.js';
import { discoverHistoricManifests } from '../packages/core/dist/manifest/detect.js';
import { isYamlAvailable } from './helpers/yaml-available.js';
import { createTestRepo } from './helpers/git-fixture.js';
import { runDepBlame } from '../packages/core/dist/engine.js';
import { renderEventTable } from '../packages/core/dist/render/table.js';

test('manifest: parsePnpmLockfile parses v6 and v9 importers correctly', async () => {
  const pnpmV6Content = `
lockfileVersion: '6.0'
importers:
  .:
    dependencies:
      react:
        specifier: ^18.2.0
        version: 18.2.0
    devDependencies:
      typescript:
        specifier: ^5.0.0
        version: 5.0.4
`;

  const map = await parsePnpmLockfile(pnpmV6Content);
  if (!map) {
    // --omit=optional contract: no yaml parser means no per-package detail.
    // Callers degrade to a low-fidelity `(lockfile)` event, never silence.
    assert.ok(!(await isYamlAvailable()), 'pnpm parsing must not return null when yaml is installed');
    return;
  }
  assert.equal(map.size, 2);
  assert.equal(map.get('react')?.version, '18.2.0');
  assert.equal(map.get('react')?.depType, 'dependencies');
  assert.equal(map.get('typescript')?.version, '5.0.4');
  assert.equal(map.get('typescript')?.depType, 'devDependencies');
});

test('manifest: parsePnpmLockfiles tracks every workspace importer', async () => {
  const content = `
lockfileVersion: '9.0'
importers:
  .:
    dependencies:
      a:
        specifier: ^1.0.0
        version: 1.0.0
  packages/app:
    dependencies:
      b:
        specifier: ^2.0.0
        version: 2.0.1
`;
  const res = await parsePnpmLockfiles(content);
  if (!res) {
    // --omit=optional contract: see above.
    assert.ok(!(await isYamlAvailable()), 'pnpm parsing must not return null when yaml is installed');
    return;
  }
  assert.equal(res.ok, true);
  assert.ok(res.maps.get('package.json')?.has('a'));
  assert.equal(res.maps.get('packages/app/package.json')?.get('b')?.version, '2.0.1');
});

test('manifest: historic discovery streams progress', async () => {
  const repo = await createTestRepo();
  try {
    await repo.commitFile('package.json', { name: 'root' }, 'root');
    await repo.commitFile('packages/a/package.json', { name: 'a' }, 'workspace');
    const seen = [];
    const res = await discoverHistoricManifests(repo.repoDir, 300, undefined, (n) => seen.push(n));
    assert.ok(res.paths.includes('package.json'));
    assert.ok(res.paths.includes('packages/a/package.json'));
    assert.ok(seen.length >= 1);
    assert.equal(seen[seen.length - 1], res.paths.length);
  } finally {
    repo.cleanup();
  }
});

test('manifest: corrupt package.json reports ok:false instead of empty', async () => {
  const res = parsePackageJson('{ invalid json');
  assert.equal(res.ok, false);
  assert.equal(res.entries.size, 0);
});

test('manifest: parseYarnLockfile parses Yarn v1 and Berry formats', async () => {
  const yarnV1Content = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"react@^18.2.0":
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"

"@types/node@^20.0.0":
  version "20.1.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.1.0.tgz"
`;

  const res = await parseYarnLockfile(yarnV1Content);
  assert.equal(res.ok, true);
  const map = res.entries;
  assert.equal(map.size, 2);
  assert.equal(map.get('react')?.version, '18.2.0');
  assert.equal(map.get('@types/node')?.version, '20.1.0');
  // Lockfile entries are resolved, never declared-direct.
  assert.equal(map.get('react')?.isDirect, false);
});

test('manifest: yarn multi-version names warn instead of silently winning', async () => {
  const content = `
# yarn lockfile v1
"left-pad@^1.0.0":
  version "1.0.0"
"left-pad@^1.3.0":
  version "1.3.0"
`;
  const res = await parseYarnLockfile(content);
  assert.equal(res.ok, true);
  assert.ok(res.note && res.note.includes('left-pad'));
});

test('manifest: parseBunLockfile parses JSONC format with comments', async () => {
  const bunContent = `
// Bun lockfile
{
  "lockfileVersion": 1,
  "packages": {
    "": {
      "dependencies": {
        "zod": "^3.22.0"
      },
    },
    "node_modules/zod": {
      "version": "3.22.4"
    }
  }
}
`;

  const map = parseBunLockfile(bunContent);
  assert.equal(map.size, 1);
  assert.equal(map.get('zod')?.version, '3.22.4');
});

test('manifest: parseBunLockfiles supports workspaces + array packages', async () => {
  const content = JSON.stringify({
    lockfileVersion: 1,
    workspaces: {
      '': { name: 'root', dependencies: { a: '^1.0.0' } },
      'packages/app': { name: 'app', dependencies: { b: '^2.0.0' } }
    },
    packages: {
      'a@1.0.5': ['a@1.0.5', 'npm:a', {}, 'sha'],
      'b@2.1.0': ['b@2.1.0', 'npm:b', {}, 'sha']
    }
  });
  const res = parseBunLockfiles(content);
  assert.equal(res.ok, true);
  assert.equal(res.maps.get('package.json')?.get('a')?.version, '1.0.5');
  assert.equal(res.maps.get('packages/app/package.json')?.get('b')?.version, '2.1.0');
});

test('manifest: binary bun.lockb reports ok:false', async () => {
  const res = parseBunLockfiles('{"lockfileVersion":\0binary');
  assert.equal(res.ok, false);
});

test('manifest & monorepo: tracks multiple workspace manifests independently', async () => {
  const repo = await createTestRepo();
  try {
    // 1. Root commit with workspaces
    await repo.commitFile(
      'package.json',
      {
        name: 'my-monorepo',
        private: true,
        workspaces: ['packages/*']
      },
      'initial monorepo setup'
    );

    // 2. Commit adding web workspace with react
    await repo.commitFile(
      'packages/web/package.json',
      {
        name: 'web',
        dependencies: { react: '18.2.0' }
      },
      'feat(web): add react'
    );

    // 3. Commit adding api workspace with express
    await repo.commitFile(
      'packages/api/package.json',
      {
        name: 'api',
        dependencies: { express: '4.18.2' }
      },
      'feat(api): add express'
    );

    const res = await runDepBlame({ cwd: repo.repoDir, silent: true });
    assert.equal(res.events.length, 2);

    const webEvent = res.events.find((e) => e.package === 'react');
    assert.ok(webEvent);
    assert.equal(webEvent.manifest, 'packages/web/package.json');

    const apiEvent = res.events.find((e) => e.package === 'express');
    assert.ok(apiEvent);
    assert.equal(apiEvent.manifest, 'packages/api/package.json');
  } finally {
    repo.cleanup();
  }
});

test('render: collapses multi-manifest bulk changes unless verbose is requested', () => {
  const events = [];
  for (let i = 1; i <= 6; i++) {
    events.push({
      package: `pkg-${i}`,
      type: 'updated',
      from: '1.0.0',
      to: '2.0.0',
      date: '2026-09-28T10:00:00Z',
      commit: 'abc1234',
      author: 'Author',
      message: 'chore: bump all packages',
      manifest: `packages/pkg-${i}/package.json`,
      depType: 'dependencies'
    });
  }

  const collapsedOutput = renderEventTable(events, { verbose: false, collapseThreshold: 5 });
  assert.ok(collapsedOutput.includes('collapsed'));
  assert.ok(collapsedOutput.includes('6 changes (6 updated) across'));

  const expandedOutput = renderEventTable(events, { verbose: true, collapseThreshold: 5 });
  assert.ok(!expandedOutput.includes('collapsed'));
  assert.ok(expandedOutput.includes('pkg-1'));
  assert.ok(expandedOutput.includes('pkg-6'));
});
