import test from 'node:test';
import assert from 'node:assert/strict';
import { parsePnpmLockfile } from '../packages/core/dist/manifest/lockfiles/pnpm.js';
import { parseYarnLockfile } from '../packages/core/dist/manifest/lockfiles/yarn.js';
import { parseBunLockfile } from '../packages/core/dist/manifest/lockfiles/bun.js';
import { createTestRepo } from './helpers/git-fixture.js';
import { runDepBlame } from '../packages/core/dist/engine.js';
import { renderEventTable } from '../packages/core/dist/render/table.js';

test('manifest: parsePnpmLockfile parses v6 and v9 importers correctly', async () => {
  const pnpmV6Content = `
lockfileVersion: '6.0'
importers:
  .:
    dependencies:
      react:
        specifier: ^18.2.0
        version: 18.2.0
    devDependencies:
      typescript:
        specifier: ^5.0.0
        version: 5.0.4
`;

  const map = await parsePnpmLockfile(pnpmV6Content);
  assert.equal(map.size, 2);
  assert.equal(map.get('react')?.version, '18.2.0');
  assert.equal(map.get('react')?.depType, 'dependencies');
  assert.equal(map.get('typescript')?.version, '5.0.4');
  assert.equal(map.get('typescript')?.depType, 'devDependencies');
});

test('manifest: parseYarnLockfile parses Yarn v1 and Berry formats', async () => {
  const yarnV1Content = `
# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1

"react@^18.2.0":
  version "18.2.0"
  resolved "https://registry.yarnpkg.com/react/-/react-18.2.0.tgz"

"@types/node@^20.0.0":
  version "20.1.0"
  resolved "https://registry.yarnpkg.com/@types/node/-/node-20.1.0.tgz"
`;

  const map = await parseYarnLockfile(yarnV1Content);
  assert.equal(map.size, 2);
  assert.equal(map.get('react')?.version, '18.2.0');
  assert.equal(map.get('@types/node')?.version, '20.1.0');
});

test('manifest: parseBunLockfile parses JSONC format with comments', async () => {
  const bunContent = `
// Bun lockfile
{
  "lockfileVersion": 1,
  "packages": {
    "": {
      "dependencies": {
        "zod": "^3.22.0"
      },
    },
    "node_modules/zod": {
      "version": "3.22.4"
    }
  }
}
`;

  const map = parseBunLockfile(bunContent);
  assert.equal(map.size, 1);
  assert.equal(map.get('zod')?.version, '3.22.4');
});

test('manifest & monorepo: tracks multiple workspace manifests independently', async () => {
  const repo = await createTestRepo();
  try {
    // 1. Root commit with workspaces
    await repo.commitFile(
      'package.json',
      {
        name: 'my-monorepo',
        private: true,
        workspaces: ['packages/*']
      },
      'initial monorepo setup'
    );

    // 2. Commit adding web workspace with react
    await repo.commitFile(
      'packages/web/package.json',
      {
        name: 'web',
        dependencies: { react: '18.2.0' }
      },
      'feat(web): add react'
    );

    // 3. Commit adding api workspace with express
    await repo.commitFile(
      'packages/api/package.json',
      {
        name: 'api',
        dependencies: { express: '4.18.2' }
      },
      'feat(api): add express'
    );

    const res = await runDepBlame({ cwd: repo.repoDir, silent: true });
    assert.equal(res.events.length, 2);

    const webEvent = res.events.find((e) => e.package === 'react');
    assert.ok(webEvent);
    assert.equal(webEvent.manifest, 'packages/web/package.json');

    const apiEvent = res.events.find((e) => e.package === 'express');
    assert.ok(apiEvent);
    assert.equal(apiEvent.manifest, 'packages/api/package.json');
  } finally {
    repo.cleanup();
  }
});

test('render: collapses multi-manifest bulk changes unless verbose is requested', () => {
  const events = [];
  for (let i = 1; i <= 6; i++) {
    events.push({
      package: `pkg-${i}`,
      type: 'updated',
      from: '1.0.0',
      to: '2.0.0',
      date: '2026-09-28T10:00:00Z',
      commit: 'abc1234',
      author: 'Author',
      message: 'chore: bump all packages',
      manifest: `packages/pkg-${i}/package.json`,
      depType: 'dependencies'
    });
  }

  const collapsedOutput = renderEventTable(events, { verbose: false, collapseThreshold: 5 });
  assert.ok(collapsedOutput.includes('collapsed'));
  assert.ok(collapsedOutput.includes('packages updated across'));

  const expandedOutput = renderEventTable(events, { verbose: true, collapseThreshold: 5 });
  assert.ok(!expandedOutput.includes('collapsed'));
  assert.ok(expandedOutput.includes('pkg-1'));
  assert.ok(expandedOutput.includes('pkg-6'));
});
